### ISSUE TITLE
DUB warnings

### ISSUE THREAD

**Issue by denizzzka** [funkwerk/serialized#2]
```
Fetching serialized 1.1.0 (getting selected version)...
Selected package unit-threaded 0.7.55 does not match the dependency specification ~>1 in package prettyprint. Need to "dub upgrade"?
Selected package unit-threaded 0.7.55 does not match the dependency specification ~>1 in package dshould. Need to "dub upgrade"?
```

**Comment by FeepingCreature** [comment]
I'll fix it tomorrow. There's no reason to use those outdated libs.

edit: In the meantime, you can ignore it though.

**Comment by denizzzka** [comment]
Oh, ok

**Comment by FeepingCreature** [comment]
Oh wait I see, the deps want unit-threaded >1. Hm, that should be a unittest only dependency honestly, but right now, is there any reason you can't use newer unit-threaded in the project?

**Comment by denizzzka** [comment]
> but right now, is there any reason you can't use newer unit-threaded in the project?

Hmm, I am not use it. It is added only by dependency by `serialized`

**Comment by FeepingCreature** [comment]
That's odd. Could you check your `dub.selections.json`, see which version it selects? `serialized` doesn't force a `0.x` `unit-threaded`. Maybe delete `dub.selections.json`, then do `dub fetch unit-threaded` and `dub test` to recreate it? I don't know if dub always checks for more recent versions if an old copy is available locally.

**Comment by denizzzka** [comment]
Oh, I'm sorry, you're right - it came from somewhere else from another DUB package what already removed from dependencies

**Comment by denizzzka** [comment]
Looks like it catches dependencies, provided by `prettyprint` and `dshould`
