### ISSUE TITLE
Support of different encodings?

### ISSUE THREAD

**Issue by denizzzka** [funkwerk/serialized#3]
Hi! It is possible to add automatic transcoding documents with line like:
```
<?xml version="1.0" encoding="WINDOWS-1251"?>
```
?

For now I transcode it by hardcode before deserialization:
```D
                import std.encoding;
		auto ws = cast(Windows1251String) xml_doc_string;
		string res;
		transcode(ws, res);
```

**Comment by FeepingCreature** [comment]
Hi, the XML decoders use `dxml`. [To quote](http://jmdavisprog.com/docs/dxml/0.4.0/dxml_parser.html): "Regardless of what the XML declaration says (if present), any range of char will be treated as being encoded in UTF-8". Maybe you could feed it a Latin1String if you already knew what format the xml data was? Check `text.xml.Parser` for comparison. But note that as opposed to JSON, the XML loader is pretty allocation happy, so there's not much point to not just transcoding the document upfront.

We handle this sort of thing by using `Content-Type` only. Once text leaves the network layer, it's pure UTF8.
